### ISSUE TITLE
Cross-repo referencing 

### ISSUE THREAD

**Issue by xmcai2016** [pln-planning-tools/MapLight#382]
Starmap throws an error when the nested children GitHub Issues are from different repos. Due to the nature of our cross-functional collaborations, one project can include 3-5 different repos and it'd be hugely beneficial if Starmap could render our roadmap.

**Comment by AlexxNica** [comment]
Starmap should be able to render roadmaps with issues from different repositories.. @xmcai2016 could you share the URL for the roadmap you're trying to render so we can check?

**Comment by xmcai2016** [comment]
@AlexxNica https://starmap.site/roadmap/github.com/data-preservation-programs/spade/issues/19#view=list is the Spade roadmap we built. Look at GitHub Issue for the 2nd milestone (#22), I had to create a duplicate Issue in the Spade repo. The original [Issue](https://github.com/data-preservation-programs/spade-reputation-service/issues/2) i wanted to use is linked inside this dupe Issue, which belongs to a different repo. When I used the original Issue for Starmap, the whole map breaks and does not render.

**Comment by SgtPooki** [comment]
If any repos are private, there's no way to render them currently since there is no auth, and we're using tokens from an ipfs bot account.

https://github.com/data-preservation-programs/spade-reputation-service repo doesn't exist for me, implying it's non-existent or private.

Please let us know if there's some other issue we didn't catch.
